add_test([=[BwtreeInitTest.HandlesInitialization]=]  /Users/hataesung/Desktop/3-2/CP/project3/release/bin/bwtree_test [==[--gtest_filter=BwtreeInitTest.HandlesInitialization]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[BwtreeInitTest.HandlesInitialization]=]  PROPERTIES WORKING_DIRECTORY /Users/hataesung/Desktop/3-2/CP/project3/release/test SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[BwtreeTest.ConcurrentRandomInsert]=]  /Users/hataesung/Desktop/3-2/CP/project3/release/bin/bwtree_test [==[--gtest_filter=BwtreeTest.ConcurrentRandomInsert]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[BwtreeTest.ConcurrentRandomInsert]=]  PROPERTIES WORKING_DIRECTORY /Users/hataesung/Desktop/3-2/CP/project3/release/test SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[BwtreeTest.ConcurrentMixed]=]  /Users/hataesung/Desktop/3-2/CP/project3/release/bin/bwtree_test [==[--gtest_filter=BwtreeTest.ConcurrentMixed]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[BwtreeTest.ConcurrentMixed]=]  PROPERTIES WORKING_DIRECTORY /Users/hataesung/Desktop/3-2/CP/project3/release/test SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[BwtreeTest.ConcurrentSkewedInsert]=]  /Users/hataesung/Desktop/3-2/CP/project3/release/bin/bwtree_test [==[--gtest_filter=BwtreeTest.ConcurrentSkewedInsert]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[BwtreeTest.ConcurrentSkewedInsert]=]  PROPERTIES WORKING_DIRECTORY /Users/hataesung/Desktop/3-2/CP/project3/release/test SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
set(  bwtree_test_TESTS BwtreeInitTest.HandlesInitialization BwtreeTest.ConcurrentRandomInsert BwtreeTest.ConcurrentMixed BwtreeTest.ConcurrentSkewedInsert)
